version: '3.1'

services:
  db:
    image: mariadb:10.3
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: notSecureChangeMe
      MYSQL_DATABASE: airports
      

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1

  airportDatabaseCreator:
     image: maven:3.8.3-jdk-11-slim
     volumes:
      - ./java:/usr/src/airportDatabaseCreator
      - ./maven-repo:/root/.m2
     working_dir: /usr/src/airportDatabaseCreator
     command: mvn compile exec:java
     